site_name: PPS Unidad 0 - Tarea Tu_nombre
theme:
  name: material

nav:
  - Inicio: index.md
  - Git: git.md
  - GitHub Actions: gitActions.md
  - GitHub Pages: gitPages.md
  - Docker: docker.md
  - Conclusiones: conclusiones.md
  
docs_dir: docs 
